export default [
  { label: 'DBS Bank Limited', value: 'DBS Bank Limited' },
  { label: 'Oversea-Chinese Banking Corp Limited', value: 'Oversea-Chinese Banking Corp Limited' },
  { label: 'United Overseas Bank Limited', value: 'United Overseas Bank Limited' },
  { label: 'Australia & New Zealand Banking Group Limited', value: 'Australia & New Zealand Banking Group Limited' },
  { label: 'Bangkok Bank Public Company Limited', value: 'Bangkok Bank Public Company Limited' },
  { label: 'Bank Of America, N.A.', value: 'Bank Of America, N.A.' },
  { label: 'Bank Of China Limited', value: 'Bank Of China Limited' },
  { label: 'Bank Of India', value: 'Bank Of India' },
  { label: 'Bank Of Tokyo-Mitsubishi UFJ, Limited', value: 'Bank Of Tokyo-Mitsubishi UFJ, Limited' },
  { label: 'BNP Paribas', value: 'BNP Paribas' },
  { label: 'Chinatrust Commercial Bank Co. Limited', value: 'Chinatrust Commercial Bank Co. Limited' },
  { label: 'CIMB Bank Berhad', value: 'CIMB Bank Berhad' },
  { label: 'Citibank N.A.', value: 'Citibank N.A.' },
  { label: 'Commerzbank Aktiengesellschaft', value: 'Commerzbank Aktiengesellschaft' },
  { label: 'Crédit Agricole Corporate And Investment Bank', value: 'Crédit Agricole Corporate And Investment Bank' },
  { label: 'Deutsche Bank AG', value: 'Deutsche Bank AG' },
  { label: 'DNB Bank ASA', value: 'DNB Bank ASA' },
  { label: 'Far Eastern Bank Limited', value: 'Far Eastern Bank Limited' },
  { label: 'First Commercial Bank', value: 'First Commercial Bank' },
  { label: 'HL Bank', value: 'HL Bank' },
  { label: 'ICICI Bank Limited', value: 'ICICI Bank Limited' },
  { label: 'Indian Bank', value: 'Indian Bank' },
  { label: 'Indian Overseas Bank', value: 'Indian Overseas Bank' },
  { label: 'Industrial & Commercial Bank Of China', value: 'Industrial & Commercial Bank Of China' },
  { label: 'Intesa Sanpaolo S.P.A.', value: 'Intesa Sanpaolo S.P.A.' },
  { label: 'JPMorgan Chase Bank, N.A.', value: 'JPMorgan Chase Bank, N.A.' },
  { label: 'Korea Exchange Bank', value: 'Korea Exchange Bank' },
  { label: 'Landesbank Baden- Wurttemberg', value: 'Landesbank Baden- Wurttemberg' },
  { label: 'Malayan Banking Berhad', value: 'Malayan Banking Berhad' },
  { label: 'Mizuho Bank Limited', value: 'Mizuho Bank Limited' },
  { label: 'National Australia Bank Limited', value: 'National Australia Bank Limited' },
  { label: 'Nordea Bank Finland PLC', value: 'Nordea Bank Finland PLC' },
  { label: 'PT Bank Negara Indonesia (Persero) TBK', value: 'PT Bank Negara Indonesia (Persero) TBK' },
  { label: 'RHB Bank Berhad', value: 'RHB Bank Berhad' },
  { label: 'Skandinaviska Enskilda Banken AB (Publ)', value: 'Skandinaviska Enskilda Banken AB (Publ)' },
  { label: 'Societe Generale', value: 'Societe Generale' },
  { label: 'Standard Chartered Bank', value: 'Standard Chartered Bank' },
  { label: 'State Bank Of India', value: 'State Bank Of India' },
  { label: 'Sumitomo Mitsui Banking Corporation', value: 'Sumitomo Mitsui Banking Corporation' },
  { label: 'Svenska Handelsbanken AB (Publ)', value: 'Svenska Handelsbanken AB (Publ)' },
  { label: 'The Bank Of East Asia Limited', value: 'The Bank Of East Asia Limited' },
  { label: 'The Hongkong And Shanghai Banking Corporation Limited', value: 'The Hongkong And Shanghai Banking Corporation Limited' },
  { label: 'The Royal Bank Of Scotland PLC', value: 'The Royal Bank Of Scotland PLC' },
  { label: 'UBS AG', value: 'UBS AG' },
  { label: 'UCO Bank', value: 'UCO Bank' },
];
