export default [
  { label: 'Business Expenses', value: 'BEXP' },
  { label: 'Bonus Payment', value: 'BONU' },
  { label: 'Cable TV bill', value: 'CBTV' },
  { label: 'Credit Card Payment', value: 'CCRD' },
  { label: 'Charity Payment', value: 'CHAR' },
  { label: 'Collection payment', value: 'COLL' },
  { label: 'Commission', value: 'COMM' },
  { label: 'Carpark charges', value: 'CPKC' },
  { label: 'Cash Disbursement', value: 'CSDB' },
  { label: 'Debit Card Payment', value: 'DCRD' },
  { label: 'Dividend', value: 'DIVD' },
  { label: 'Dental services', value: 'DNTS' },
  { label: 'Education', value: 'EDUC' },
  { label: 'Payment of Fees and Charges', value: 'FCPM' },
  { label: 'Foreign Worker Levy', value: 'FWLV' },
  { label: 'Purchase Sale Of Goods', value: 'GDDS' },
  { label: 'Government Insurance', value: 'GOVI' },
  { label: 'Goods & Services Tax', value: 'GSTX' },
  { label: 'Hospital Care', value: 'HSPC' },
  { label: 'Instalment Hire Purchase Agreement', value: 'IHRP' },
  { label: 'Insurance Premium', value: 'INSU' },
  { label: 'Intra Company Payment', value: 'INTC' },
  { label: 'Interest', value: 'INTE' },
  { label: 'Investment & Securities', value: 'INVS' },
  { label: 'Invoice Payment', value: 'IVPT' },
  { label: 'Loan', value: 'LOAN' },
  { label: 'Medical Service', value: 'MDCS' },
  { label: 'Net income Tax', value: 'NITX' },
  { label: 'OTHER', value: 'OTHR' },
  { label: 'Telephone bill', value: 'PHON' },
  { label: 'Property tax', value: 'PTXP' },
  { label: 'Road Tax', value: 'RDTX' },
  { label: 'Rebate', value: 'REBT' },
  { label: 'Refund', value: 'REFU' },
  { label: 'Rent', value: 'RENT' },
  { label: 'Salary Payment', value: 'SALA' },
  { label: 'Study', value: 'STDY' },
  { label: 'Supplier Payment', value: 'SUPP' },
  { label: 'Tax Payment', value: 'TAXS' },
  { label: 'Telco Bill', value: 'TBIL' },
  { label: 'Town Council Service Charges', value: 'TCSC' },
  { label: 'Trade Services', value: 'TRAD' },
  { label: 'Treasure payment', value: 'TREA' },
  { label: 'Transport', value: 'TRPT' },
  { label: 'Utilities', value: 'UBIL' },
  { label: 'With Holding', value: 'WHLD' },
  { label: 'Account management', value: 'ACCT' },
  { label: 'Opening Fee', value: 'OFEE' },
  { label: 'Trust Fund', value: 'TRFD' },
  { label: 'Value Added Tax Payment', value: 'VATX' },
  { label: 'Advance Payment', value: 'ADVA' },
  { label: 'Agricultural Transfer', value: 'AGRT' },
  { label: 'Air', value: 'AIRB' },
  { label: 'Allowance', value: 'ALLW' },
  { label: 'Alimony payment', value: 'ALMY' },
  { label: 'Anaesthesia payment ', value: 'ANTS' },
  { label: 'Account Receivable Entry', value: 'AREN' },
  { label: 'Baby Bonus Scheme', value: 'BBSC' },
  { label: 'Child Benefit', value: 'BECH' },
  { label: 'Unemployment Disability Benefit', value: 'BENE' },
  { label: 'Back Office Conversion Entry', value: 'BOCE' },
  { label: 'Bus', value: 'BUSB' },
  { label: 'Cash Management Transfer', value: 'CASH' },
  { label: 'Capital Building', value: 'CBFF' },
  { label: 'Credit Card Bill', value: 'CDBL' },
  { label: 'Credit Payment with Cashback', value: 'CDCB' },
  { label: 'Cash Disbursement', value: 'CDCD' },
  { label: 'Original Credit', value: 'CDOC' },
  { label: 'Quasi Cash', value: 'CDQC' },
  { label: 'Cancellation Fee', value: 'CFEE' },
  { label: 'Car Loan Principal Repayment', value: 'CLPR' },
  { label: 'Commodity Transfer', value: 'CMDT' },
  { label: 'Commercial Payment', value: 'COMC' },
  { label: 'Consumer Third Party Consolidate Payment', value: 'COMT' },
  { label: 'Cost', value: 'COST' },
  { label: 'Copyright', value: 'CPYR' },
  { label: 'Company Social Loan Payment To Bank', value: 'CSLP' },
  { label: 'Convalescent Care facility', value: 'CVCF' },
  { label: 'Debit Collection Payment', value: 'DBTC' },
  { label: 'Deposit', value: 'DEPT' },
  { label: 'Derivatives', value: 'DERI' },
  { label: 'Durable Medical Equipment', value: 'DMEQ' },
  { label: 'Electricity Bill', value: 'ELEC' },
  { label: 'Energies', value: 'ENRG' },
  { label: 'Estate Tax', value: 'ESTX' },
  { label: 'Ferry', value: 'FERB' },
  { label: 'Foreign Exchange', value: 'FREX' },
  { label: 'Gas Bill', value: 'GASB' },
  { label: 'Purchase Sale Of Goods And Services', value: 'GDSV' },
  { label: 'Government Payment', value: 'GOVT' },
  { label: 'Purchase Sale Of Goods And Service With Cash Back', value: 'GSCB' },
  { label: 'Hedging', value: 'HEDG' },
  { label: 'Housing Loan Repayment', value: 'HLRP' },
  { label: 'Home Health Care', value: 'HLTC' },
  { label: 'Health Insurance', value: 'HLTI' },
  { label: 'Housing Tax', value: 'HSTX' },
  { label: 'Irrevocable Credit Card Payment', value: 'ICCP' },
  { label: 'Intermediate Care Facility', value: 'ICRF' },
  { label: 'Irrevocable Debit Card Payment', value: 'IDCP' },
  { label: 'Insurance Premium Car', value: 'INPC' },
  { label: 'Labour Insurance', value: 'LBRI' },
  { label: 'License Fee', value: 'LICF' },
  { label: 'Life Insurance', value: 'LIFI' },
  { label: 'Liquidity Management', value: 'LIMA' },
  { label: 'Loan Repayment', value: 'LOAR' },
  { label: 'Long Term Care Facility', value: 'LTCF' },
  { label: 'Multiple Service Type', value: 'MSVC' },
  { label: 'Netting', value: 'NETT' },
  { label: 'Not Otherwise Specified', value: 'NOWS' },
  { label: 'Network Charge', value: 'NWCH' },
  { label: 'Network Communication', value: 'NWCM' },
  { label: 'Other Telecom Related Bill', value: 'OTLC' },
  { label: 'Preauthorised Debit', value: 'PADD' },
  { label: 'Payroll', value: 'PAYR' },
  { label: 'Pension Payment', value: 'PENS' },
  { label: 'Point Of Purchase Entry', value: 'POPE' },
  { label: 'Property Insurance', value: 'PPTI' },
  { label: 'Price Payment', value: 'PRCP' },
  { label: 'Precious Metal', value: 'PRME' },
  { label: 'Payment Terms', value: 'PTSP' },
  { label: 'Re-presented Check Entry', value: 'RCKE' },
  { label: 'Receipt Payment', value: 'RCPT' },
  { label: 'Recurring Instalment Payment', value: 'RINP' },
  { label: 'Railway', value: 'RLWY' },
  { label: 'Royalties', value: 'ROYA' },
  { label: 'Savings', value: 'SAVG' },
  { label: 'Royalties', value: 'ROYA' },
  { label: 'Purchase Sale of Services', value: 'SCVE' },
  { label: 'Securities', value: 'SECU' },
  { label: 'Social Security Benefits', value: 'SSBE' },
  { label: 'Subscription', value: 'SUBS' },
  { label: 'Telephone-Initiated Transaction', value: 'TELI' },
  { label: 'Vision Care', value: 'VIEW' },
  { label: 'Internet-Initiated Transaction', value: 'WEBI' },
  { label: 'Water Bill', value: 'WTER' },
];
